In [1]:
import pandas as pd

In [2]:
foods = pd.read_csv('data/sr-legacy/apr2019/food_nutrient.csv')
foods

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,1283674,167512,1003,5.88,1,46.0,NaN,NaN,NaN,NaN,NaN
1,1283675,167512,1007,3.50,1,46.0,NaN,NaN,NaN,NaN,NaN
2,1283676,167512,1062,1286.00,0,49.0,NaN,NaN,NaN,NaN,NaN
3,1283677,167512,1079,1.20,1,46.0,NaN,NaN,NaN,NaN,NaN
4,1283678,167512,1089,2.12,1,46.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
644120,1927794,175304,1175,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN
644121,1927795,175304,1242,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN
644122,1927796,175304,1246,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN
644123,1927797,175304,1198,14.00,0,12.0,NaN,NaN,NaN,NaN,NaN
644124,1927798,175304,1180,106.40,0,12.0,NaN,NaN,NaN,NaN,NaN

In [3]:
nutrient_ids = (
    pd.read_csv('data/nutrient.csv')
    .set_index('id'))
nutrient_ids

                             name unit_name  nutrient_nbr     rank
id
1002                     Nitrogen         G         202.0    500.0
1003                      Protein         G         203.0    600.0
1004            Total lipid (fat)         G         204.0    800.0
1005  Carbohydrate, by difference         G         205.0   1110.0
1007                          Ash         G         207.0   1000.0
...                           ...       ...           ...      ...
2025                       22:6 c         G         839.0  15250.0
2026                       20:2 c         G         840.0  14250.0
2028          trans-beta-Carotene        UG         321.2   7444.0
2029               trans-Lycopene        UG         337.2   7534.0
2032         Cryptoxanthin, alpha        UG         335.0   7461.0

[232 rows x 4 columns]

In [4]:
foods['nutrient_name'] = foods['nutrient_id'].map(nutrient_ids['name'])
foods['nutrient_unit'] = foods['nutrient_id'].map(nutrient_ids['unit_name'])
foods

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name,nutrient_unit
0,1283674,167512,1003,5.88,1,46.0,NaN,NaN,NaN,NaN,NaN,Protein,G
1,1283675,167512,1007,3.50,1,46.0,NaN,NaN,NaN,NaN,NaN,Ash,G
2,1283676,167512,1062,1286.00,0,49.0,NaN,NaN,NaN,NaN,NaN,Energy,kJ
3,1283677,167512,1079,1.20,1,46.0,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
4,1283678,167512,1089,2.12,1,46.0,NaN,NaN,NaN,NaN,NaN,"Iron, Fe",MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
644120,1927794,175304,1175,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin B-6,MG
644121,1927795,175304,1242,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN,"Vitamin E, added",MG
644122,1927796,175304,1246,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN,"Vitamin B-12, added",UG
644123,1927797,175304,1198,14.00,0,12.0,NaN,NaN,NaN,NaN,NaN,Betaine,MG
644124,1927798,175304,1180,106.40,0,12.0,NaN,NaN,NaN,NaN,NaN,"Choline, total",MG

In [5]:
categories = (
    pd.read_csv('data/food_category.csv')
    .set_index('id'))
categories

    code                          description
id
1    100               Dairy and Egg Products
2    200                     Spices and Herbs
3    300                           Baby Foods
4    400                        Fats and Oils
5    500                     Poultry Products
6    600           Soups, Sauces, and Gravies
7    700          Sausages and Luncheon Meats
8    800                    Breakfast Cereals
9    900              Fruits and Fruit Juices
10  1000                        Pork Products
11  1100    Vegetables and Vegetable Products
12  1200                Nut and Seed Products
13  1300                        Beef Products
14  1400                            Beverages
15  1500       Finfish and Shellfish Products
16  1600          Legumes and Legume Products
17  1700        Lamb, Veal, and Game Products
18  1800                       Baked Products
19  1900                               Sweets
20  2000              Cereal Grains and Pasta
21  2100                           Fast Foods
22  2200      Meals, Entrees, and Side Dishes
23  2500                               Snacks
24  3500  American Indian/Alaska Native Foods
25  3600                     Restaurant Foods
26  4500       Branded Food Products Database
27  2600            Quality Control Materials
28  1410                  Alcoholic Beverages

In [6]:
food_ids = (
    pd.read_csv('data/sr-legacy/apr2019/food.csv')
    .assign(food_category = lambda df: df['food_category_id'].map(categories['description']))
    .set_index('fdc_id'))
food_ids

,data_type,description,food_category_id,publication_date,food_category
fdc_id,,,,,
167512,sr_legacy_food,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",18,2019-04-01,Baked Products
167513,sr_legacy_food,"Pillsbury, Cinnamon Rolls with Icing, refriger...",18,2019-04-01,Baked Products
167514,sr_legacy_food,"Kraft Foods, Shake N Bake Original Recipe, Coa...",18,2019-04-01,Baked Products
167515,sr_legacy_food,"George Weston Bakeries, Thomas English Muffins",18,2019-04-01,Baked Products
167516,sr_legacy_food,"Waffles, buttermilk, frozen, ready-to-heat",18,2019-04-01,Baked Products
...,...,...,...,...,...
175300,sr_legacy_food,"Game meat, buffalo, water, cooked, roasted",17,2019-04-01,"Lamb, Veal, and Game Products"
175301,sr_legacy_food,"Game meat, elk, raw",17,2019-04-01,"Lamb, Veal, and Game Products"
175302,sr_legacy_food,"Game meat, elk, cooked, roasted",17,2019-04-01,"Lamb, Veal, and Game Products"
175303,sr_legacy_food,"Game meat, goat, raw",17,2019-04-01,"Lamb, Veal, and Game Products"
175304,sr_legacy_food,"Game meat, goat, cooked, roasted",17,2019-04-01,"Lamb, Veal, and Game Products"

In [7]:
foods['food_name'] = foods['fdc_id'].map(food_ids['description'])
foods['food_category'] = foods['fdc_id'].map(food_ids['food_category'])
foods

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,nutrient_name,nutrient_unit,food_name,food_category
0,1283674,167512,1003,5.88,1,46.0,NaN,NaN,NaN,NaN,NaN,Protein,G,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",Baked Products
1,1283675,167512,1007,3.50,1,46.0,NaN,NaN,NaN,NaN,NaN,Ash,G,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",Baked Products
2,1283676,167512,1062,1286.00,0,49.0,NaN,NaN,NaN,NaN,NaN,Energy,kJ,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",Baked Products
3,1283677,167512,1079,1.20,1,46.0,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",Baked Products
4,1283678,167512,1089,2.12,1,46.0,NaN,NaN,NaN,NaN,NaN,"Iron, Fe",MG,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",Baked Products
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644120,1927794,175304,1175,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin B-6,MG,"Game meat, goat, cooked, roasted","Lamb, Veal, and Game Products"
644121,1927795,175304,1242,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN,"Vitamin E, added",MG,"Game meat, goat, cooked, roasted","Lamb, Veal, and Game Products"
644122,1927796,175304,1246,0.00,0,68.0,NaN,NaN,NaN,NaN,NaN,"Vitamin B-12, added",UG,"Game meat, goat, cooked, roasted","Lamb, Veal, and Game Products"
644123,1927797,175304,1198,14.00,0,12.0,NaN,NaN,NaN,NaN,NaN,Betaine,MG,"Game meat, goat, cooked, roasted","Lamb, Veal, and Game Products"
644124,1927798,175304,1180,106.40,0,12.0,NaN,NaN,NaN,NaN,NaN,"Choline, total",MG,"Game meat, goat, cooked, roasted","Lamb, Veal, and Game Products"

sugars_details = [
 'Maltose',
 'Sucrose',
 'Lactose',
 'Fructose',
 'Galactose',
 'Glucose (dextrose)',
]

vitamins_details = [
 'Vitamin E, added',
 'Vitamin B-12, added',
 'Folate, DFE',
 'Folate, food',
 'Tocopherol, beta', #vitE
 'Tocopherol, delta', #vitE
 'Tocopherol, gamma', #vitE
 'Tocotrienol, alpha', #vitE
 'Tocotrienol, beta', #vitE
 'Tocotrienol, delta', #vitE
 'Tocotrienol, gamma', #vitE
 'Vitamin D2 (ergocalciferol)',
 'Vitamin D3 (cholecalciferol)',
 'Vitamin K (Dihydrophylloquinone)',
 'Vitamin K (Menaquinone-4)',
]

neaas = [
 'Arginine',
 'Aspartic acid',
 'Proline',
 'Serine',
 'Glutamic acid',
 'Alanine',
 'Glycine',
]


phythosterols = [
 'Phytosterols',
 'Beta-sitosterol',
 'Campesterol',
 'Hydroxyproline',
 'Stigmasterol',
]
    
other_nutrients = [
 'Theobromine', # caffeine-like in chocolate
 'Caffeine',
 'Choline, total', #aa-like
 'Betaine', # choline-like
 'Folic acid', #B9 synthetic
 'Fluoride, F',
 'Water',
 'Starch', # mostly NaNs
 'Fatty acids, total trans', #Barely anythin in whole foods
]

omega6s = [
 '18:2 n-6 c,c',
 '18:3 n-6 c,c,c',
 '20:2 n-6 c,c',
 '20:3 n-6',
 '20:4 n-6',
]
    
omega3s = [
 '18:3 n-3 c,c,c (ALA)',
 '20:3 n-3',
 '20:5 n-3 (EPA)',
 '22:5 n-3 (DPA)',
 '22:6 n-3 (DHA)',
]

macros = [
 'Energy',
 'Carbohydrate, by difference',
 'Total lipid (fat)',
 'Protein',
 'Fiber, total dietary',
]

macros_details =  [
 'Sugars, total including NLEA',
 'Fatty acids, total monounsaturated',
 'Fatty acids, total polyunsaturated',
 'Fatty acids, total saturated',
#  'Cholesterol',
]

minerals = [
 'Calcium, Ca',
 'Copper, Cu',
 'Iron, Fe',
 'Magnesium, Mg',
 'Manganese, Mn',
 'Phosphorus, P',
 'Potassium, K',
 'Selenium, Se',
 'Sodium, Na',
 'Zinc, Zn'
]
    
vitamins = [
 'Thiamin', #B1
 'Riboflavin', #B2
 'Niacin', #B3
 'Pantothenic acid', #B5
 'Vitamin B-6',
 'Folate, total', #B9
 'Vitamin B-12',
#  'Vitamin A, IU',
 'Vitamin A, RAE',
 'Vitamin C, total ascorbic acid',
 'Vitamin D (D2 + D3)',
#  'Vitamin D (D2 + D3), International Units',
 'Vitamin E (alpha-tocopherol)',
 'Vitamin K (phylloquinone)',
]

caretonoids = [
 'Lycopene',
 'Lutein + zeaxanthin',
 'Carotene, alpha',
 'Carotene, beta',
 'Retinol',
 'Cryptoxanthin, beta',
              ]
coi = macros + macros_details + minerals + vitamins + caretonoids + aas

In [8]:
nutrients = dict(
macros = [
 'Energy',
 'Carbs',
 'Fat',
 'Protein',
 'Fiber',
],

macros_details =  [
 'Sugars',
 'Monounsaturated fat',
 'Polyunsaturated fat',
 'Saturated fat',
 'Cholesterol',
],

minerals = [
 'Calcium',
 'Copper',
 'Iron',
 'Magnesium',
 'Manganese',
 'Phosphorus',
 'Potassium',
 'Selenium',
 'Sodium',
 'Zinc'
],

vitamins = [
 'Vitamin B1 (Thiamin)',
 'Vitamin B2 (Riboflavin)',
 'Vitamin B3 (Niacin)',
 'Vitamin B4 (Pantothenic acid)',
 'Vitamin B6',
 'Vitamin B9 (Folate)',
 'Vitamin B12',
 # 'Vitamin A, IU',
 'Vitamin A',
 'Vitamin C',
 'Vitamin D (D2 + D3)',
 # 'Vitamin D (D2 + D3), International Units',
 'Vitamin E',
 'Vitamin K',
],
    
# eaas plus cysteine and tyrosine
aas = [
 'Cystine',
 'Histidine',
 'Isoleucine',
 'Leucine',
 'Lysine',
 'Methionine',
 'Phenylalanine',
 'Threonine',
 'Tryptophan',
 'Tyrosine',
 'Valine',
],

caretonoids = [
 'Lycopene',
 'Lutein + zeaxanthin',
 'alpha-Carotene',
 'beta-Carotene',
#  'Retinol', # all zeros
 'beta-Cryptoxanthin',
],
)

coi =  [x for sub in nutrients.values() for x in sub]
# ['Shrt_Desc']

In [9]:
foods_piv = (
    foods
    .pivot_table(index='food_name',  columns='nutrient_name', values='amount')
    .rename(
        columns = {
            'Carbohydrate, by difference': 'Carbs', 'Total lipid (fat)': 'Fat',
            'Sugars, total including NLEA': 'Sugars', 'Fiber, total dietary': 'Fiber',
            'Thiamin': 'Vitamin B1 (Thiamin)', 'Vitamin B-6': 'Vitamin B6', 'Vitamin B-12': 'Vitamin B12',
            'Riboflavin': 'Vitamin B2 (Riboflavin)', 'Niacin': 'Vitamin B3 (Niacin)',
            'Pantothenic acid': 'Vitamin B4 (Pantothenic acid)', 'Folate, total': 'Vitamin B9 (Folate)',
            'Fatty acids, total monounsaturated': 'Monounsaturated fat', 'Fatty acids, total polyunsaturated': 'Polyunsaturated fat',
            'Fatty acids, total saturated': 'Saturated fat', #'food_name': 'Shrt_Desc',
            'Calcium, Ca': 'Calcium', 'Copper, Cu': 'Copper', 'Iron, Fe': 'Iron', 'Magnesium, Mg': 'Magnesium',
            'Manganese, Mn': 'Manganese', 'Phosphorus, P': 'Phosphorus', 'Potassium, K': 'Potassium', 'Selenium, Se': 'Selenium',
            'Sodium, Na': 'Sodium', 'Zinc, Zn': 'Zinc',
            'Vitamin C, total ascorbic acid': 'Vitamin C', 'Vitamin A, RAE': 'Vitamin A',
            'Vitamin K (phylloquinone)': 'Vitamin K', 'Vitamin E (alpha-tocopherol)': 'Vitamin E',
            'Carotene, alpha': 'alpha-Carotene', 'Carotene, beta': 'beta-Carotene',
            'Cryptoxanthin, beta': 'beta-Cryptoxanthin'})
            [coi])
foods_piv.index.name = 'Shrt_Desc'
# foods_piv

In [10]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

food_grps = {
    'grains': ['Quinoa,uncooked', "Oats", 'Barley,hulled', 'Barley,pearled,raw',
               'Buckwheat', "Rice,brown,long-grain,raw", 'Wild rice,raw',
               'Millet,raw', 'Bulgur,dry', 'Spelt,uncooked', 'Wheat,durum',
               'Wheat,soft white', 'Wheat,hard red winter', 'Sorghum grain',
               'Wheat,kamut khorasan,uncooked', 'Amaranth grain,uncooked',
               'Rice,white,long-grain,regular,raw,unenriched', 'Semolina,unenriched',
               'Triticale', 'Teff,uncooked', 'Rye grain'],
    'vegetables': ['Brussels sprouts,raw', 'Beets,raw', 'Broccoli,raw',
                   'Cauliflower,raw', 'Eggplant,raw', ],
    'greens': ['Kale,raw', 'Spinach,raw', 'Lettuce,cos or romaine,raw',
               'Chard,swiss,raw', 'Arugula,raw', 'Collards,raw',
               'Lettuce,iceberg (includes crisphead types),raw', 'Beet greens,raw',
               'Mustard greens,raw', 'Cabbage,chinese (pak-choi),raw',
               'Cabbage,raw', ],
    'legumes': ['Beans,black turtle,mature seeds,raw', 'Lentils,raw',
                'Lentils,pink or red,raw', 'Beans,snap,green,raw',
                'Soybeans,green,raw', 'Beans,pinto,mature seeds,sprouted,raw',
                'Beans,snap,yellow,raw', 'Beans,adzuki,mature seeds,raw',
                'Beans,black,mature seeds,raw',
                'Beans,black turtle,mature seeds,raw',
                'Beans,cranberry (roman),mature seeds,raw',
                'Beans,french,mature seeds,raw', 'Beans,navy,mature seeds,raw',
                'Beans,kidney,all types,mature seeds,raw',
                'Beans,pink,mature seeds,raw', 'Beans,pinto,mature seeds,raw',
                'Beans,small white,mature seeds,raw',
                'Beans,white,mature seeds,raw', 'Soybeans,mature seeds,raw',
                'Broadbeans (fava beans),mature seeds,raw', 'Peas,green,raw',
                'Chickpeas (garbanzo beans,bengal gram),mature seeds,raw',
                'Peas,green,split,mature seeds,raw'],
    'nuts': [f'Nuts,{x.lower()}' for x  in ['Beechnuts,dried', 'Brazilnuts,dried,unblanched',
             'Butternuts,dried', 'Cashew nuts,raw',
             'Hazelnuts or filberts', 'Hickorynuts,dried',
             'Macadamia nuts,raw', 'Pilinuts,dried',
             'Pine nuts,dried', 'Pistachio nuts,raw', 'Walnuts,english', 'Almonds',
             'Coconut meat,dried (desiccated),not sweetened']] + ['Peanuts,all types,raw'],
    'fruits': ["Apples,raw,with skin",
               'Pineapple,raw,all varieties', 'Plums,raw', 'Pears,raw',
               'Apricots,raw', 'Avocados,raw,all commercial varieties',
               'Blackberries,frozen,unsweetened', 'Blueberries,raw',
               'Cranberries,raw', 'Raspberries,raw', 'Clementines,raw',
               'Strawberries,raw', 'Dates,medjool', 'Plantains,green,raw',
               'Pomegranates,raw', 'Bananas,raw', 'Plantains,yellow,raw',
               'Kiwifruit,green,raw', 'Figs,dried,uncooked', 'Oranges,raw,all commercial varieties',
               'Apricots,dried,sulfured,uncooked', 'Olives,ripe,canned (small-extra large)']
    }

'Barley, hulled', # simlar to pearled
'Wheat, soft white' # similar to hard red
'Triticale', 'Semolina, unenriched',
'Beans, snap, yellow, raw',  #similar to green
'Beans, cranberry (roman), mature seeds, raw',
'Beans, french, mature seeds, raw', 'Beans, navy, mature seeds, raw',
'Beans, white, mature seeds, raw', 
'Beans, pink, mature seeds, raw', 
'Beechnuts, dried', 
'Butternuts, dried', 
'Hickorynuts, dried',
'Pilinuts, dried',

In [11]:
food_grps = {
    'grains': ['Quinoa, uncooked', 'Oats', 'Barley, pearled, raw',
               'Buckwheat', 'Rice, brown, long-grain, raw', 'Wild rice, raw',
               'Millet, raw', 'Bulgur, dry', 'Spelt, uncooked', 'Wheat, durum',
               'Wheat, hard red winter', 'Sorghum grain',
               'Wheat, kamut khorasan, uncooked', 'Amaranth grain, uncooked',
               'Rice, white, long-grain, regular, raw, unenriched', 
               'Teff, uncooked', 'Rye grain'],
    'vegetables': ['Brussels sprouts, raw', 'Beets, raw', 'Broccoli, raw', 'Corn grain, yellow', 
                   'Cauliflower, raw', 'Eggplant, raw', 'Tomatoes, red, ripe, raw, year round average',
                   'Peas, green, frozen, unprepared'],
    'greens': ['Kale, raw', 'Spinach, raw', 'Lettuce, cos or romaine, raw',
               'Chard, swiss, raw', 'Arugula, raw', 'Collards, raw',
               'Lettuce, iceberg (includes crisphead types), raw', 'Beet greens, raw',
               'Mustard greens, raw', 'Cabbage, chinese (pak-choi), raw',
               'Cabbage, raw', ],
    'legumes': ['Beans, black turtle, mature seeds, raw', 'Lentils, raw',
                'Lentils, pink or red, raw', 'Beans, snap, green, raw',
                'Soybeans, green, raw', 'Beans, pinto, mature seeds, sprouted, raw',
                'Beans, adzuki, mature seeds, raw',
                'Beans, black, mature seeds, raw',
                'Beans, kidney, all types, mature seeds, raw',
                'Beans, pinto, mature seeds, raw',
                'Beans, small white, mature seeds, raw',
                'Soybeans, mature seeds, raw',
                'Broadbeans (fava beans), mature seeds, raw', 'Peas, green, raw',
                'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw',
                'Peas, green, split, mature seeds, raw'],
    'nuts': [f'Nuts, {x.lower()}' for x in ['Brazilnuts, dried, unblanched',
             'Cashew nuts, raw',
             'Hazelnuts or filberts', 
             'Macadamia nuts, raw', 
             'Pine nuts, dried', 'Pistachio nuts, raw', 'Walnuts, english',
             'Coconut meat, dried (desiccated), not sweetened']] + ['Peanuts, all types, raw'],
    'fruits': ["Apples, raw, with skin",
               'Pineapple, raw, all varieties', 'Plums, raw', 'Pears, raw',
               'Apricots, raw', 'Avocados, raw, all commercial varieties',
               'Blackberries, frozen, unsweetened', 'Blueberries, raw',
               'Cranberries, raw', 'Raspberries, raw', 'Clementines, raw',
               'Strawberries, raw', 'Dates, medjool', 'Plantains, green, raw',
               'Pomegranates, raw', 'Bananas, raw', 'Plantains, yellow, raw',
               'Kiwifruit, green, raw', 'Figs, dried, uncooked', 'Oranges, raw, all commercial varieties',
               'Apricots, dried, sulfured, uncooked', 'Olives, ripe, canned (small-extra large)',
               'Raisins, dark, seedless'],
    'meats': ['Fish, salmon, atlantic, farmed, raw', 'Fish, salmon, atlantic, wild, raw',
              'Fish, cod, atlantic, raw', 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw',
              'Pork, fresh, ground, raw',  'Beef, grass-fed, ground, raw', 'Egg, whole, raw, fresh', ]
             
    }

foods_piv[foods_piv.index.str.lower().str.contains('beef.*ground')]#.fillna(0).style.background_gradient()

In [12]:
# foods_all = foods_piv.copy()
foods_piv.index = foods_piv.index.str.replace(" \(Includes foods for USDA's Food Distribution Program\)", '').str.capitalize()
# food_names = [fn.replace(',', ', ') for fn_list in food_grps.values() for fn in fn_list]
food_names = [fn for fn_list in food_grps.values() for fn in fn_list]
foods_sub = foods_piv.loc[food_names].copy()
# Test if foods are found
foods_sub[foods_sub.isna().all(axis=1)].index.to_list()

[]

In [13]:
foods_sub.loc['Oats', 'Sugars'] = 1.1
foods_sub.loc['Oats', 'Selenium'] = 28.9
foods_sub.loc['Oats', 'Vitamin E'] = 0.42
foods_sub.loc['Oats', 'Vitamin K'] = 2
foods_sub.loc['Oats', 'beta-Carotene'] = 0
foods_sub.loc['Oats', 'alpha-Carotene'] = 0
foods_sub.loc['Oats', 'beta-Cryptoxanthin'] = 0
foods_sub.loc['Oats', 'Lycopene'] = 0
foods_sub.loc['Oats', 'Lutein + zeaxanthin'] = 180

foods_sub.loc['Quinoa, uncooked', 'Sugars'] = 6.1
foods_sub.loc['Quinoa, uncooked', 'Vitamin C'] = 0
foods_sub.loc['Buckwheat', 'Sugars'] = 1.9
foods_sub.loc['Millet, raw', 'Sugars'] = 1.5
# # used entry for semolina flour as th evalues were very similar
# foods_sub.loc['Semolina, unenriched', 'Sugars'] = 0.7
# foods_sub.loc['Triticale', 'Sugar_Tot_(g)'] = 1
# foods_sub.loc['Triticale', 'Fiber_TD_(g)'] = 14.6

foods_sub = foods_sub.reset_index()  # TODO remove this
# foods_sub.to_csv('sr-dec2019.csv', index=False)

In [14]:
# coi = ['Shrt_Desc'] + [x for sub in nutrients.values() for x in sub]

# foods_all = read_csv('nutrimap/data/sr-dec2019.csv', usecols=coi, index_col=0)
# foods_all.index = foods_all.index.str.capitalize()
# food_names = [fn.replace(',', ', ') for fn_list in food_grps.values() for fn in fn_list]
# foods_sub = foods_piv.loc[food_names].copy()
# foods = foods_all.loc[[x for sl in food_grps.values() for x in sl]].copy()

# flowers = foods_all.reset_index().copy()
# na_indices = flowers.isnull().any(axis=1).to_numpy().nonzero()
# na_foods = flowers.iloc[na_indices]['Shrt_Desc'].values
# flowers = flowers.dropna()
# print(na_foods)

# RDI
df_rdi = pd.read_csv('data/matched_rdi_sr_nih.csv', comment='#')
flowers = foods_sub.set_index('Shrt_Desc')


def get_rdi(row):
    '''Calculate the RDI'''
    new_row = pd.Series()
    for col_name in row.index:
        new_row.loc[col_name] = round(
            100 * row[col_name] / df_rdi.loc[
                df_rdi['MatchedNutrient'] == col_name, 'Amount'].values[0], 1)
    return new_row

flowers = flowers.apply(get_rdi, axis=1)

In [15]:
flowers['Category'] = ''
for grp_name in food_grps:
    new_food = [x for x in food_grps[grp_name]]  # if x not in na_foods]
    flowers.loc[new_food, 'Category'] = grp_name
flowers = flowers.reset_index().copy()

In [16]:
flowers[['Shrt_Desc', 'Category']]

                                            Shrt_Desc    Category
0                                    Quinoa, uncooked      grains
1                                                Oats      grains
2                                Barley, pearled, raw      grains
3                                           Buckwheat      grains
4                        Rice, brown, long-grain, raw      grains
5                                      Wild rice, raw      grains
6                                         Millet, raw      grains
7                                         Bulgur, dry      grains
8                                     Spelt, uncooked      grains
9                                        Wheat, durum      grains
10                             Wheat, hard red winter      grains
11                                      Sorghum grain      grains
12                    Wheat, kamut khorasan, uncooked      grains
13                           Amaranth grain, uncooked      grains
14  Rice, white, long-grain, regular, raw, unenriched      grains
15                                     Teff, uncooked      grains
16                                          Rye grain      grains
17                              Brussels sprouts, raw  vegetables
18                                         Beets, raw  vegetables
19                                      Broccoli, raw  vegetables
20                                 Corn grain, yellow  vegetables
21                                   Cauliflower, raw  vegetables
22                                      Eggplant, raw  vegetables
23       Tomatoes, red, ripe, raw, year round average  vegetables
24                    Peas, green, frozen, unprepared  vegetables
25                                          Kale, raw      greens
26                                       Spinach, raw      greens
27                       Lettuce, cos or romaine, raw      greens
28                                  Chard, swiss, raw      greens
29                                       Arugula, raw      greens
30                                      Collards, raw      greens
31   Lettuce, iceberg (includes crisphead types), raw      greens
32                                   Beet greens, raw      greens
33                                Mustard greens, raw      greens
34                   Cabbage, chinese (pak-choi), raw      greens
35                                       Cabbage, raw      greens
36             Beans, black turtle, mature seeds, raw     legumes
37                                       Lentils, raw     legumes
38                          Lentils, pink or red, raw     legumes
39                            Beans, snap, green, raw     legumes
40                               Soybeans, green, raw     legumes
41          Beans, pinto, mature seeds, sprouted, raw     legumes
42                   Beans, adzuki, mature seeds, raw     legumes
43                    Beans, black, mature seeds, raw     legumes
44        Beans, kidney, all types, mature seeds, raw     legumes
45                    Beans, pinto, mature seeds, raw     legumes
46              Beans, small white, mature seeds, raw     legumes
47                        Soybeans, mature seeds, raw     legumes
48         Broadbeans (fava beans), mature seeds, raw     legumes
49                                   Peas, green, raw     legumes
50  Chickpeas (garbanzo beans, bengal gram), matur...     legumes
51              Peas, green, split, mature seeds, raw     legumes
52                Nuts, brazilnuts, dried, unblanched        nuts
53                             Nuts, cashew nuts, raw        nuts
54                        Nuts, hazelnuts or filberts        nuts
55                          Nuts, macadamia nuts, raw        nuts
56                             Nuts, pine nuts, dried        nuts
57                          Nuts, pistachio nuts, raw        nuts
58                             Nuts, walnuts, english        nuts
59  Nuts, coconut meat, dried (desiccated), not sw...        nuts
60                            Peanuts, all types, raw        nuts
61                             Apples, raw, with skin      fruits
62                      Pineapple, raw, all varieties      fruits
63                                         Plums, raw      fruits
64                                         Pears, raw      fruits
65                                      Apricots, raw      fruits
66            Avocados, raw, all commercial varieties      fruits
67                  Blackberries, frozen, unsweetened      fruits
68                                   Blueberries, raw      fruits
69                                   Cranberries, raw      fruits
70                                   Raspberries, raw      fruits
71                                   Clementines, raw      fruits
72                                  Strawberries, raw      fruits
73                                     Dates, medjool      fruits
74                              Plantains, green, raw      fruits
75                                  Pomegranates, raw      fruits
76                                       Bananas, raw      fruits
77                             Plantains, yellow, raw      fruits
78                              Kiwifruit, green, raw      fruits
79                              Figs, dried, uncooked      fruits
80             Oranges, raw, all commercial varieties      fruits
81                Apricots, dried, sulfured, uncooked      fruits
82           Olives, ripe, canned (small-extra large)      fruits
83                            Raisins, dark, seedless      fruits
84                Fish, salmon, atlantic, farmed, raw       meats
85                  Fish, salmon, atlantic, wild, raw       meats
86                           Fish, cod, atlantic, raw       meats
87  Chicken, broiler or fryers, breast, skinless, ...       meats
88                           Pork, fresh, ground, raw       meats
89                       Beef, grass-fed, ground, raw       meats
90                             Egg, whole, raw, fresh       meats

In [17]:
flowers.to_csv('data/clean_rdi.csv', index=False)